
CREATE TABLE public.task (
	id SERIAL PRIMARY KEY,
	name varchar(65) NOT NULL,
	description varchar(125),
	task_date timestamp,
	is_done int default 0
);

CREATE TABLE public.TARF_PUBERRORS (
	PUBID SERIAL PRIMARY KEY,
	PUBCDCLASE varchar(10) NOT NULL,
	PUBDSNOMBRE varchar(45) NOT NULL,
	PUBDSUUID varchar(45) NOT NULL,
	PUBCDDNI varchar(4),
	PUBDSDNI   varchar(20),
	PUBFEEVENTO timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PUBDSJSON varchar(32672) NOT NULL,
	PUBDSERROR varchar(32672) NOT NULL
);

CREATE TABLE public.TJAN_RESTRICCIONES (
	RESCDRESTRICCION SERIAL PRIMARY KEY,
	RESCDORDEN int NOT NULL,
	RESDSAPLICACION VARCHAR(45) NOT NULL,
	RESDSURL VARCHAR(45) NOT NULL,
	RESDSMETODO VARCHAR(10) NOT NULL,
	RESDSCOMANDO VARCHAR(45),
	RESDSESTRATEGIACAR VARCHAR(200),
	RESDSESTRATEGIANVL VARCHAR(200),
	RESDSROLES VARCHAR(100) NOT NULL,
	RESSNCARTERA int DEFAULT 0 NOT NULL,
	RESSNNIVELSEG int DEFAULT 0 NOT NULL
);

CREATE TABLE public.TJAN_DIRECTIVAS (
	DIRCDDIRECTIVA SERIAL PRIMARY KEY,
	DIRCDORDEN int NOT NULL,
	DIRDSAPLICACION VARCHAR(45) NOT NULL,
	DIRDSDIRECTIVA VARCHAR(45) NOT NULL,
	DIRDSROLES VARCHAR(120) NOT NULL
 );

CREATE TABLE public.TJAN_RECURSOS (
	RECCDRECURSO SERIAL PRIMARY KEY,
	RECCDORDEN int NOT NULL,
	RECDSAPLICACION VARCHAR(45) NOT NULL,
	RECDSRECURSO VARCHAR(45) NOT NULL,
	RECDSROLES VARCHAR(250) NOT NULL
);

INSERT INTO public.TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES (1,'appSegura','/commands','POST','*','*',0,0,NULL,NULL);

INSERT INTO public.TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES(2,'appSegura','/tasks*','GET',NULL,'*',0,0,NULL,NULL);

-- recurso para storage api v2
INSERT INTO public.TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES(6,'appSegura','/upload/v2','POST',NULL,'*',0,0,NULL,NULL);
INSERT INTO public.TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES(7,'appSegura','/download/v2*','GET',NULL,'*',0,0,NULL,NULL);
INSERT INTO public.TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES(8,'appSegura','/files/v2','GET',NULL,'*',0,0,NULL,NULL);

INSERT INTO public.TJAN_RECURSOS(RECCDORDEN, RECDSAPLICACION, RECDSRECURSO, RECDSROLES)
    VALUES(1,'appSegura','/*','*');

INSERT INTO public.TJAN_DIRECTIVAS(DIRCDORDEN, DIRDSAPLICACION, DIRDSDIRECTIVA, DIRDSROLES)
    VALUES(1,'appSegura','gui.button.create','*');
