apiVersion: v1
kind: Secret
metadata:
  name: arq-ref-demo-config
  namespace: arq-ref-demo # por favor colocar siempre el nombre del namespace definido en 'namespace.yml'
type: Opaque
stringData:
  # en 'data' se debe colocar cada archivo que se va llevar como configuracion al configmap
  application.yml: |
    server:
      host: localhost
      port: 8443
      compression:
        enabled: true
        mime-types: application/json
        min-response-size: 2048
      error:
        includeStacktrace: ALWAYS
      mq:
        host: xxx             # No aplica para AWS
        port: 0               # No aplica para AWS
        queue-manager: xxx    # No aplica para AWS
        channel: xxx          # No aplica para AWS
        username: xxx         # No aplica para AWS
        password: xxx         # No aplica para AWS

        # https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jms/listener/AbstractPollingMessageListenerContainer.html#setReceiveTimeout-long-
        receive-timeout: 5000
        publishDestination:   <topico de mi aplicacion>
        subscribeDestination: <cola de mi aplicacion>
        errorDestination:     <topico error de mi aplicacion>
        #uiDestination: xxxxxx # No aplica para AWS

        # Numero de consumidores concurrentes (Minimo-Maximo)
        # https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jms/listener/DefaultMessageListenerContainer.html#setConcurrency-java.lang.String-
        concurrency: 1-3
        aws:
          concurrency: 10 # Numero de mensajes a leer por cada consumidor concurrente en cada Polling al servicio de amazon.

        #developerMode: false  # No aplica para AWS. Usar https://github.com/localstack/localstack.

    app.env: DemoApp con broker SQS-SNS!!

    cloud:
      aws:
        stack:
          # para evitar este error cuando se despliega en kubernetes
          # https://vostpmde37.proteccion.com.co:10443/ARQ_Referencia/arq_referencia_proteccion/issues/1
          auto: false
        region:
          static: us-east-1
        credentials:
          instanceProfile: false
          use-default-aws-credentials-chain: true

    storage:
      cloud:
        bucket: demo-bucket

    logging:
      level:
        root: WARN
        co.com.proteccion: DEBUG
        org.springframework.http.codec.json: TRACE

    securedApplication:
      name: appSegura                                       # Nombre App. Debe corresponder a un nombre de app asignado en Azure AD o Azure B2C
      idAppProteccion: 132                                  # Este id debe corresponder a un identificador interno de proteccion dado por Arquitectura.
      corsAllowOrigin: ANY                                  # Configuracion CORS 'Access-Control-Allow-Origin', ANY es equivalente a '*'
      corsAllowHeader: myHeaderName1, myHeaderName2         # Configuracion CORS 'Access-Control-Allow-Headers'. Si se desea permitir uno o mas headers adicionales en la peticion web
      corsExposeHeader: MyTestHeader                        # Configuracion CORS 'Access-Control-Expose-Headers'. Igual que el anterior pero en la respuesta.
      validateTokenIP: false
      whiteList: 10.100.224.251                              #Lista de direcciones Ips excentas de validacion de token JWT
      busBaseUrl: https://vaxtpmde71.proteccion.com.co:444   #URL base del bus de integracion en PRUEBAS (Pdn seria 'servicios.proteccion.com.co')
      useJsonRepository: false                               #Le indica a Jano si las tablas de Restricciones, Directivas y recursos estan en BD o en archivos JSON
      janoEnabled: true                                      #Switch maestro para encender o apagar Jano
      azure: ## Bloque de configuraciones de azure
        scopeEmpleados: # scope de empleados
          clientId: 69f46a95-55ce-412d-8cfc-8c8b0ef18dbc                # El client ID debe solicitarse
          tenant: f47dcce4-02e7-4d88-a659-a2d0bbe170e7                  # Este tenant id siempre es el mismo para Empleados (pru o pdn)
          clientSecret: 1BOGY9Y1UuUuLGUdVH9Eti-EJEMPLO-    # El client Secret debe solicitarse



