-- En esta tabla la arquitectura guarda los mensajes que no se puedan procesar.

CREATE TABLE TARF_PUBERRORS (
	PUBID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PUBCDCLASE varchar(10) NOT NULL,
	PUBDSNOMBRE varchar(45) NOT NULL,
	PUBDSUUID varchar(45) NOT NULL,
	PUBCDDNI varchar(4),
	PUBDSDNI   varchar(20),
	PUBFEEVENTO timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PUBDSJSON varchar(32672) NOT NULL,
	PUBDSERROR varchar(32672) NOT NULL,
    PRIMARY KEY (PUBID)
);