CREATE TABLE TJAN_RESTRICCIONES (
	RESCDRESTRICCION int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	RESCDORDEN int NOT NULL,
	RESDSAPLICACION VARCHAR(45) NOT NULL,
	RESDSURL VARCHAR(45) NOT NULL,
	RESDSMETODO VARCHAR(10) NOT NULL,
	RESDSCOMANDO VARCHAR(45),
	RESDSESTRATEGIACAR VARCHAR(200),
	RESDSESTRATEGIANVL VARCHAR(200),
	RESDSROLES VARCHAR(100) NOT NULL,
	RESSNCARTERA int DEFAULT 0 NOT NULL,
	RESSNNIVELSEG int DEFAULT 0 NOT NULL,
	PRIMARY KEY (RESCDRESTRICCION)
);

CREATE TABLE TJAN_DIRECTIVAS (
	DIRCDDIRECTIVA int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DIRCDORDEN int NOT NULL,
	DIRDSAPLICACION VARCHAR(45) NOT NULL,
	DIRDSDIRECTIVA VARCHAR(45) NOT NULL,
	DIRDSROLES VARCHAR(120) NOT NULL,
	PRIMARY KEY (DIRCDDIRECTIVA)
 );

CREATE TABLE TJAN_RECURSOS (
	RECCDRECURSO int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	RECCDORDEN int NOT NULL,
	RECDSAPLICACION VARCHAR(45) NOT NULL,
	RECDSRECURSO VARCHAR(45) NOT NULL,
	RECDSROLES VARCHAR(250) NOT NULL,
    PRIMARY KEY(RECCDRECURSO)
);

INSERT INTO TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES (1,'appSegura','/commands','POST','*','*',0,0,NULL,NULL);

INSERT INTO TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES(2,'appSegura','/tasks*','GET',NULL,'*',0,0,NULL,NULL);

-- recurso para storage api v2
INSERT INTO TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES(6,'appSegura','/upload/v2','POST',NULL,'*',0,0,NULL,NULL);
INSERT INTO TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES(7,'appSegura','/download/v2*','GET',NULL,'*',0,0,NULL,NULL);
INSERT INTO TJAN_RESTRICCIONES(RESCDORDEN, RESDSAPLICACION, RESDSURL, RESDSMETODO, RESDSCOMANDO, RESDSROLES, RESSNCARTERA, RESSNNIVELSEG, RESDSESTRATEGIACAR, RESDSESTRATEGIANVL)
    VALUES(8,'appSegura','/files/v2','GET',NULL,'*',0,0,NULL,NULL);

INSERT INTO TJAN_RECURSOS(RECCDORDEN, RECDSAPLICACION, RECDSRECURSO, RECDSROLES)
    VALUES(1,'appSegura','/*','*');

INSERT INTO TJAN_DIRECTIVAS(DIRCDORDEN, DIRDSAPLICACION, DIRDSDIRECTIVA, DIRDSROLES)
    VALUES(1,'appSegura','gui.button.create','*');
