CREATE TABLE TARF_PUBERRORS 
(
  PUBID NUMBER GENERATED ALWAYS AS IDENTITY 
, PUBCDCLASE VARCHAR2(10) NOT NULL 
, PUBDSNOMBRE VARCHAR2(45) NOT NULL 
, PUBDSUUID VARCHAR2(45) NOT NULL 
, PUBCDDNI VARCHAR2(4) 
, PUBDSDNI VARCHAR2(20) 
, PUBFEEVENTO DATE DEFAULT sysdate NOT NULL 
, PUBDSJSON VARCHAR2(4000) NOT NULL 
, PUBDSERROR VARCHAR2(4000) NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    PUBID 
  )
  ENABLE 
);
